# Generated by Django 4.2.6 on 2023-10-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_student_admission_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cancel_admission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='sub_category',
            field=models.CharField(choices=[('2a', '2a'), ('2b', '2b'), ('cat-1', 'cat-1')], default='--', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='year_completed',
            field=models.IntegerField(default=0),
        ),
    ]
