# Generated by Django 4.2.6 on 2023-10-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_student_cancel_admission_student_sub_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sub_category',
            field=models.CharField(choices=[('--', '--'), ('2a', '2a'), ('2b', '2b'), ('cat-1', 'cat-1')], default='--', max_length=20),
        ),
    ]
