# Generated by Django 6.0.4 on 2026-04-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_student_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='fees_details',
            name='repeater',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='Is_lateral',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='merit_no',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='category',
            field=models.CharField(choices=[('SC', 'SC'), ('SNQ', 'SNQ'), ('Others', 'Others'), ('ST', 'ST')], default='Others', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='dep',
            field=models.CharField(choices=[('Automobile', 'Automobile'), ('Computer Science', 'Computer Science'), ('E and C', 'E and C'), ('E and E', 'E and E'), ('Civil', 'Civil'), ('Mechanical', 'Mechanical'), ('Dummy', 'Dummy')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='sub_category',
            field=models.CharField(choices=[('--', '--'), ('2a', '2a'), ('2b', '2b'), ('3a', '3a'), ('3b', '3b'), ('cat-1', 'cat-1'), ('GM', 'GM'), ('SC', 'SC'), ('ST', 'ST')], default='--', max_length=20),
        ),
    ]
