# Generated by Django 6.0.4 on 2026-04-18 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_fees_details_repeater_student_is_lateral_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fees_Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=1)),
                ('category', models.CharField(choices=[('SC', 'SC'), ('SNQ', 'SNQ'), ('Others', 'Others'), ('ST', 'ST')], default='Others', max_length=20)),
                ('repeater', models.BooleanField(default=False)),
                ('is_lateral', models.BooleanField(default=False)),
                ('total_fees', models.IntegerField(default=0)),
                ('tution_fees', models.IntegerField(default=0)),
                ('admission_fees', models.IntegerField(default=0)),
                ('id_fees', models.IntegerField(default=0)),
                ('management_fees', models.IntegerField(default=0)),
                ('lib_fees', models.IntegerField(default=0)),
                ('assn_fees', models.IntegerField(default=0)),
                ('rr_fees', models.IntegerField(default=0)),
                ('swf_fees', models.IntegerField(default=0)),
                ('twf_fees', models.IntegerField(default=0)),
                ('lab_fees', models.IntegerField(default=0)),
                ('sp_fees', models.IntegerField(default=0)),
                ('nss_fees', models.IntegerField(default=0)),
                ('dev_fees', models.IntegerField(default=0)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.academic_year')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('year', 'academic_year', 'category', 'repeater', 'is_lateral'), name='unique_fee_structure_combination')],
            },
        ),
    ]
