# Generated by Django 6.0.4 on 2026-04-19 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_fees_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='fees_details',
            name='is_detained',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Detentions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=1)),
                ('is_detention_removed', models.BooleanField(default=False)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.academic_year')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
        ),
    ]
