# Generated by Django 6.0.4 on 2026-05-02 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_fees_details_is_detained_detentions'),
    ]

    operations = [
        migrations.AddField(
            model_name='fees_structure',
            name='red_cross_fees',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='history',
            name='red_cross_fees',
            field=models.IntegerField(default=0),
        ),
    ]
